# Generated by Django 3.1.5 on 2021-01-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=50)),
                ('directedby', models.CharField(max_length=50)),
                ('releasedate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie_Model',
        ),
    ]
